server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles: 0.5,0.95,0.99,1.0
            percentiles-histogram: true