apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: profile-monitor
  labels:
    app: profile-app
spec:
  endpoints:
    - port: web
      scheme: http
      path: /actuator/prometheus
      interval: 15s
  selector:
    matchLabels:
      app: profile-app
  namespaceSelector:
    matchNames:
      - app
