apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
  - image: exxbrain/krakend
  local: {}
deploy:
  helm:
    releases:
      - name: krakend
        chartPath: krakend-chart