apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: { }
  artifacts:
  - image: exxbrain/arch-krakend
  local: {}
deploy:
  helm:
    releases:
      - name: krakend
        namespace: api-gateway
        chartPath: krakend-chart
        artifactOverrides:
          image: exxbrain/arch-krakend